CREATE TABLE "cards" (
      id TEXT PRIMARY KEY,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      object TEXT NOT NULL,
      oracle_id TEXT NOT NULL,
      multiverse_ids JSONB DEFAULT '[]'::jsonb NOT NULL,
      tcgplayer_id INTEGER,
      cardmarket_id INTEGER,
      name TEXT NOT NULL,
      printed_name TEXT,
      lang TEXT NOT NULL,
      released_at TEXT,
      uri TEXT,
      scryfall_uri TEXT,
      layout TEXT,
      highres_image BOOLEAN NOT NULL,
      image_status TEXT,
      image_uris JSONB NOT NULL,
      mana_cost TEXT,
      cmc INTEGER,
      type_line TEXT,
      oracle_text TEXT,
      colors JSONB DEFAULT '[]'::jsonb NOT NULL,
      color_identity JSONB DEFAULT '[]'::jsonb NOT NULL,
      keywords JSONB DEFAULT '[]'::jsonb NOT NULL,
      legalities JSONB NOT NULL,
      games JSONB DEFAULT '[]'::jsonb NOT NULL,
      reserved BOOLEAN NOT NULL,
      game_changer BOOLEAN NOT NULL,
      foil BOOLEAN NOT NULL,
      nonfoil BOOLEAN NOT NULL,
      finishes JSONB DEFAULT '[]'::jsonb NOT NULL,
      oversized BOOLEAN NOT NULL,
      promo BOOLEAN NOT NULL,
      reprint BOOLEAN NOT NULL,
      variation BOOLEAN NOT NULL,
      set_id TEXT,
      set TEXT,
      set_name TEXT,
      set_type TEXT,
      set_uri TEXT,
      set_search_uri TEXT,
      scryfall_set_uri TEXT,
      rulings_uri TEXT,
      prints_search_uri TEXT,
      collector_number TEXT,
      digital BOOLEAN NOT NULL,
      rarity TEXT,
      card_back_id TEXT,
      artist TEXT,
      artist_ids JSONB DEFAULT '[]'::jsonb NOT NULL,
      illustration_id TEXT,
      border_color TEXT,
      frame TEXT,
      full_art BOOLEAN NOT NULL,
      flavor_text TEXT,
      textless BOOLEAN NOT NULL,
      booster BOOLEAN NOT NULL,
      story_spotlight BOOLEAN NOT NULL,
      edhrec_rank INTEGER,
      prices JSONB NOT NULL,
      related_uris JSONB NOT NULL,
      purchase_uris JSONB NOT NULL
    );